# Generated by Django 4.1.1 on 2022-09-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='country',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
