# Generated by Django 4.1.1 on 2022-09-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_detail_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
