# Generated by Django 4.0.6 on 2022-09-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_alter_country_options_alter_detail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
