# Generated by Django 4.0.6 on 2022-09-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_alter_product_code_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='country',
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='new_app.country'),
            preserve_default=False,
        ),
    ]
