# Generated by Django 4.0.6 on 2022-09-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_remove_detail_country_product_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('code_product', 'country')},
        ),
    ]
