# Generated by Django 4.0.6 on 2022-09-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_alter_product_unique_together_detail_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='new_app.country'),
        ),
    ]
