# Generated by Django 4.0.6 on 2022-09-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0013_year_alter_detail_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year_number',
            field=models.IntegerField(unique=True),
        ),
    ]
