# Generated by Django 4.1.1 on 2022-10-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0014_alter_year_year_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='new_app.year'),
        ),
    ]
