# Generated by Django 3.2.16 on 2022-10-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0016_import_export_for_db_matrix_x_and_c_for_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='K',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
