# Generated by Django 3.2.16 on 2022-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0017_alter_matrix_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='K',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
