# Generated by Django 4.0 on 2022-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0018_alter_matrix_k'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('economic_activity', models.CharField(max_length=50)),
                ('gdp', models.FloatField(blank=True, null=True)),
                ('year_number', models.IntegerField()),
            ],
        ),
    ]
