# Generated by Django 4.0 on 2022-10-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0019_gdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdp',
            name='year_number',
        ),
        migrations.AddField(
            model_name='gdp',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_app.year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='import_export_for_db',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.year'),
        ),
        migrations.AlterField(
            model_name='x_and_c_for_db',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.year'),
        ),
    ]
