# Generated by Django 4.0 on 2022-10-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0020_remove_gdp_year_number_gdp_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year_number',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='detail',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.year'),
        ),
    ]
