# Generated by Django 4.1.1 on 2022-10-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0021_rename_year_number_year_year_alter_detail_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdp',
            options={'verbose_name_plural': 'Gdp'},
        ),
        migrations.AlterModelOptions(
            name='import_export_for_db',
            options={'verbose_name_plural': 'Import export'},
        ),
        migrations.AlterModelOptions(
            name='matrix',
            options={'verbose_name_plural': 'Matrix'},
        ),
        migrations.AlterModelOptions(
            name='x_and_c_for_db',
            options={'verbose_name_plural': 'X and C'},
        ),
    ]
