# Generated by Django 4.1.2 on 2022-10-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0022_alter_gdp_options_alter_import_export_for_db_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(max_length=50),
        ),
    ]
